---
#Created by SrClauYT and iFail90
#Decoration: »    |     «
prefix-myserver: "§8[§bLitCube§8]"
join-msg: "§8» §aJoined the Server"
leave-msg: "§8» §cLeft the Server"

cmd-game1: "ffa join"
cmd-game2: "sw join"
cmd-game3: "help"
cmd-game4: "core"
cmd-game5: "core help"

button-game1: "§eFree For All"
button-game2: "§eGapple"
button-game3: "§eNoDebuff"
button-game4: "§eSkyWars"
button-game5: "§eBedWars"

button-cosmetic4: "Particles"
cmd-cosmetic4: "help"

#Procure tener cuidado al mome6de editar esto, no nos hacemos responsables de cualquier error que ocurra debido a una mala edición.
#Be careful when editing this, we are not responsible for any errors that occur due to bad editing.

#Server UI

Server: "§8[§bLitCube§8]§f"
Shop: "shop.example.net"
IP: "play.exemple.xyz"

#ADVANCED

content-ranks: "Ranks \n \n Test \n \n Test1 \n \n Test2 \n \n Test3 \n \n :D"

text-buyrank: "Test"
text-shop: "shop.example.net"
text-prices: "$"
text-contact: "exampleemail@tcf.com"
...
